<AbogadosScreen>:

    BoxLayout:
        orientation: "vertical"

        canvas.before:
            Color:
                rgba: 0.96, 0.97, 0.98, 1
            Rectangle:
                pos: self.pos
                size: self.size

        # TOPBAR
        BoxLayout:
            size_hint_y: None
            height: 62
            padding: [12, 10, 16, 10]
            canvas.before:
                Color:
                    rgba: 0.12, 0.16, 0.23, 1
                Rectangle:
                    pos: self.pos
                    size: self.size

            Button:
                text: "<"
                size_hint_x: None
                width: 36
                font_size: 22
                bold: True
                background_color: 0, 0, 0, 0
                color: 1,1,1,1
                on_release: root.volver()

            BoxLayout:
                orientation: "vertical"
                Label:
                    text: "ABOGADOS"
                    font_size: 18
                    bold: True
                    color: 1, 1, 1, 1
                    halign: "left"
                    text_size: self.size
                Label:
                    id: lbl_area
                    text: ""
                    font_size: 12
                    color: 0.70, 0.75, 0.85, 1
                    halign: "left"
                    text_size: self.size

        # BUSCADOR
        BoxLayout:
            size_hint_y: None
            height: 54
            padding: [16, 10, 16, 6]

            canvas.before:
                Color:
                    rgba: 0.12, 0.16, 0.23, 1
                Rectangle:
                    pos: self.pos
                    size: self.size

            TextInput:
                id: buscador
                hint_text: "Buscar abogado..."
                multiline: False
                size_hint_y: None
                height: 38
                background_color: 1, 1, 1, 1
                foreground_color: 0.1, 0.1, 0.1, 1
                hint_text_color: 0.50, 0.55, 0.65, 1
                cursor_color: 0.12, 0.16, 0.23, 1
                padding: [12, 10]
                font_size: 14
                on_text: root.filtrar(self.text)

        # LISTA
        ScrollView:
            BoxLayout:
                id: lista
                orientation: "vertical"
                padding: [16, 16, 16, 90]
                spacing: 14
                size_hint_y: None
                height: self.minimum_height