<LoginScreen>:
    BoxLayout:
        orientation: "vertical"

        canvas.before:
            Color:
                rgba: 0.96, 0.97, 0.98, 1
            Rectangle:
                pos: self.pos
                size: self.size

        padding: 30
        spacing: 20

        Widget:
            size_hint_y: None
            height: 40

        Label:
            text: "Legal App"
            font_size: 30
            bold: True
            color: 0.12, 0.16, 0.23, 1
            size_hint_y: None
            height: 50

        Label:
            text: "Accede a tu cuenta"
            color: 0.45,0.45,0.45,1
            size_hint_y: None
            height: 30

        Widget:
            size_hint_y: None
            height: 20

        BoxLayout:
            orientation: "vertical"
            padding: 20
            spacing: 15
            size_hint_y: None
            height: 260

            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [15]

            TextInput:
                id: email
                hint_text: "Email"
                multiline: False
                size_hint_y: None
                height: 48
                background_color: 1,1,1,1
                foreground_color: 0.1,0.1,0.1,1
                font_size: 16

            TextInput:
                id: password
                hint_text: "Contrasena"
                password: True
                multiline: False
                size_hint_y: None
                height: 48
                background_color: 1,1,1,1
                foreground_color: 0.1,0.1,0.1,1
                font_size: 16

            Label:
                id: error
                text: ""
                color: 1,0.3,0.3,1
                size_hint_y: None
                height: 20

            Button:
                text: "Ingresar"
                size_hint_y: None
                height: 50
                background_color: 0.12, 0.16, 0.23, 1
                color: 1,1,1,1
                font_size: 16
                on_release: root.login()

        Button:
            text: "Crear cuenta"
            size_hint_y: None
            height: 45
            background_color: 0.13, 0.77, 0.37, 1
            color: 1,1,1,1
            on_release: root.go_register()