<PrivacyScreen>:

    BoxLayout:
        orientation: "vertical"
        padding: "15dp"
        spacing: "10dp"

        canvas.before:
            Color:
                rgba: 0.95, 0.96, 0.98, 1
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: "Política de Privacidad"
            size_hint_y: None
            height: "50dp"
            font_size: "24sp"
            bold: True
            color: 0, 0, 0, 1

        ScrollView:
            do_scroll_x: False

            Label:
                id: privacy_label
                text: ""
                markup: True
                size_hint_y: None
                text_size: self.width - dp(20), None
                height: self.texture_size[1]
                padding: "10dp", "10dp"
                color: 0.15, 0.15, 0.15, 1
                font_size: "16sp"
                valign: "top"

        Button:
            text: "Volver"
            size_hint_y: None
            height: "50dp"
            background_normal: ""
            background_color: 0.23, 0.18, 0.55, 1
            color: 1, 1, 1, 1
            on_release:
                root.manager.current = "register"